In [24]:
import pandas as pd

url ='http://www.bjets.com.cn/article/jyxx/?'
links = []
for n in range(1,62):
    link = url + str(n)
    links.append(link)
    
df2 = pd.DataFrame()
for url in links:
    dfs = pd.read_html(url,header=0)
    for df in dfs:
        df2 = df2.append(df,ignore_index=True)
        
df2.to_excel('test1.xlsx',encoding='utf_8')

In [17]:
df2

             日期  成交量(吨)  成交均价(元/吨)             成交额(元)
0    2018-12-18     300       9.30     2,790.00（林业碳汇）
1    2018-12-18    2500      42.00    105,000.00（BEA）
2    2018-12-17     200      11.60     2,320.00（林业碳汇）
3    2018-12-17    1559      49.98     77,915.90（BEA）
4    2018-12-14    8450      14.50   122,525.00（林业碳汇）
5    2018-12-14    1000      50.10     50,100.00（BEA）
6    2018-12-13    1700      12.10    20,570.00（林业碳汇）
7    2018-12-13    9740      49.09    478,106.00（BEA）
8    2018-12-12   13003      52.37    681,020.00（BEA）
9    2018-12-11    5351      50.04    267,742.50（BEA）
10   2018-12-10    9001      45.55    410,035.00（BEA）
11   2018-12-06   14516      58.78    853,187.60(BEA)
12   2018-12-05    1626      57.59     93,644.40（BEA）
13   2018-12-04    5819      55.46    322,724.70（BEA）
14   2018-12-03    3731      51.64    192,654.60（BEA）
15   2018-11-30     401      50.89     20,405.00(BEA)
16   2018-11-29     225      51.29     11,540.00（BEA）
17   2018-11-28   14426      50.33    726,012.00（BEA）
18   2018-11-27    7502      50.16    376,277.00（BEA）
19   2018-11-23     559      43.59     24,366.80（BEA）
20   2018-11-22     994      41.40     41,151.60（BEA）
21   2018-11-21    1999      35.00     69,960.20（BEA）
22   2018-11-20     486      37.80     18,370.80（BEA）
23   2018-11-19     498      41.30     20,567.40（BEA）
24   2018-11-16     212      45.47      9,639.60（BEA）
25   2018-11-15       8      47.00        376.00（BEA）
26   2018-11-07     500      47.10     23,550.00（BEA）
27   2018-11-05   44000      49.42  2,174,400.00(BEA)
28   2018-11-02  116534      43.90  5,116,179.60（BEA）
29   2018-11-01   30497      43.80  1,335,768.60（BEA）
..          ...     ...        ...                ...
860  2014-02-19     350      51.70              18095
861  2014-02-18     700      51.40              35990
862  2014-02-17     550      51.50              28325
863  2014-02-14     500      51.10              25550
864  2014-02-13     500      51.80              25900
865  2014-02-12     400      51.00              20400
866  2014-02-11     300      51.00              15300
867  2014-01-30     100      50.80               5080
868  2014-01-29     100      51.00               5100
869  2014-01-28     100      50.50               5050
870  2014-01-22     100      50.20               5020
871  2014-01-21     200      50.00              10000
872  2014-01-20     200      50.10              10020
873  2014-01-17     200      50.10              10020
874  2014-01-16     200      50.10              10020
875  2014-01-14     200      53.00              10600
876  2014-01-13     500      50.00              25000
877  2014-01-10     100      50.80               5080
878  2014-01-09     200      50.65              10130
879  2014-01-08     400      50.75              20300
880  2014-01-07     500      50.00              25000
881  2014-01-02      50      51.50               2575
882  2013-12-24    1000      50.00              50000
883  2013-12-19     100      55.00               5500
884  2013-12-17     100      51.00               5100
885  2013-12-11     100      50.50               5050
886  2013-12-06     100      50.00               5000
887  2013-12-05     100      50.20               5020
888  2013-12-02     300      55.10              16530
889  2013-11-28     800      51.25              41000

[890 rows x 4 columns]